(import (chezscheme))

(define (execute-shell-command command)
  (let-values ([(in out err pid)
                (open-process-ports command (buffer-mode block) (native-transcoder))])
    (let* ((stdout (get-string-all out))
           (stderr (get-string-all err))
           (status 0))
            ;;(status process-status pid)))
      (close-output-port in)
      (close-input-port out)
      (close-input-port err)
      (values stdout stderr status))))

;; Test the function
(let-values (((stdout stderr status)
              (execute-shell-command "ls -l $HOME/a.* && echo 'This will not be printed' >&2")))
  (display "STDOUT:\n")
  (display stdout)
  (display "\nSTDERR:\n")
  (display stderr)
  (display "\nExit status: ")
  (display status)
  (newline))
